bookadoc/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('homepage',homepage,name='home'),
    path('register',registeruser,name='reg'),
    path('login',loginpage,name='login'),
    path('logout',logoutpage,name='logout'),
    path('staffreg',staff_register,name='staff_register'),

    path('searchdoctors/<dep>',search_doctors,name='search_doctors'),
    path('patientprofile',patient_profile,name='patient_profile'),
    path('editpatientprofile',edit_patient_profile,name='edit_patientprofile'),
    path('appointments',appointments,name='appointments'),
    path('createbooking/<int:uid>',createbooking,name='createbooking'),
    
    path('doctorpage',doctor_home,name='doctor_home'),
    path('doctorprofile',doctor_profilepage,name='doctor_profile'),
    path('edit_doctorprofile',edit_doctor_profile,name='edit_doctor_profile'),
    path('mybookings',mybookings,name='mybookings'),
    path('manageappointments',manage_appointments,name='manage_appointments'),
    path('approvebooking/<int:bid>',aprove_booking,name='aprove_booking'),
    path('rejectbooking/<int:bid>',reject_booking,name='reject_booking'),
    path('scheduled_appointment',scheduled_appointments,name='scheduled_appointments'),
   
    path('admindashboard',admin_dashboard,name='admin_dashboard'),
    path('aproveprofile/<int:doc_id>',aprove_profile,name='aprove_profile'),
    path('rejectprofile/<int:doc_id>',reject_profile,name='reject_profile'),
    path('aprovedprofiles',aproved_doctor_profiles,name='aproved_profiles'),
    path('rejectedprofiles',rejected_doctor_profiles,name='rejected_profiles'),
    path('alldoctors',all_doctors,name='alldoctors'),
    path('managedoctors',manage_doctors,name='manage_doctors'),
    path('profileverification',profile_verification,name='profile_verification'),
    path('allpatients',all_patients,name='allpatients'),
    path('managepatients',manage_patients,name='manage_patients'),
    path('viewpatient/<int:p_id>',view_patient,name='view_patient'),
    path('allappointments',all_appointments,name='all_appointments'),
    path('manageallappointments',manage_all_appointments,name='manage_all_appointments'),
    path('aprovedpatients',aproved_patients,name='aproved_patients'),
    path('rejctedpatients',rejected_patients,name='rejected_patients'),
    path('deleteappointment/<int:appointment_id>',delete_appointment,name='delete_appointment'),
    path('deletedoctor/<int:doctor_id>',delete_doctor,name='delete_doctor'),
    path('doctors_list',doctors_list,name='doctors_list'),
    path('deletepatient/<int:patient_id>',delete_patient,name='delete_patient'),
    path('viewdoctor/<int:doc_id>',view_doctor,name='view_doctor'),
    
    path('feedback',feedback,name='feedback'),
    path('feedbacklist',feedback_list,name='feedback_list')

   
]


doctorproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookadoctor/',include('bookadoc.urls')),
    path('',include('bookadoc.urls')),
]

if settings.DEBUG:
     
     urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

bookadoc/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class PatientPro(models.Model):

    choice = (('male','male'),('female','female'))
    
    

    profile_pic = models.ImageField(upload_to='patient_photos/', blank=True,null=True)
    patient = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.IntegerField(null=True)
    bio = models.TextField(blank=True)
    age = models.IntegerField(null=True)
    gender = models.CharField(max_length=100,choices=choice)
    blood = models.CharField(max_length=50,blank=True)
    created = models.DateField(default=timezone.now)
    def __str__(self):
        return self.patient.username


class Dprofile(models.Model):

    specs = (('dentist', 'dentist'),
             ('cardiologist', 'cardiologist'),
             ('otolaryngologist', 'otolaryngologist'),
             ('orthopedist','orthopedist'),
             ('pediatrics','pediatrics'),
             ('ophthalmologist','ophthalmologist'),
             ('gynecologist','gynecologist'),
             ('dermatologist','dermatologist'),
             ('neurologist','neurologist'),
             ('psychiatrist','psychiatrist'),
             )
    
    choice = (('male','male'),('female','female'))

    permision = (('aproved','aproved'),('rejected','rejected'),('pending','pending'))
    
    profile_pic = models.ImageField(upload_to='doctors_photos/',null=True,blank=True)
    doctor = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100,blank=True)
    phone = models.IntegerField(null=True)
    bio = models.TextField(blank=True)
    specilization = models.CharField(max_length=300, choices=specs,blank=True)
    qualifications = models.CharField(max_length=50,blank=True)
    gender = models.CharField(max_length=50,choices=choice)
    profile_status =  models.CharField(max_length=100,choices=permision,default='pending')
    location = models.CharField(max_length=100,blank=True,null=True)
    clinic_name = models.CharField(max_length=100,blank=True)
    clinic_address = models.TextField(blank=True)
    consultation_days = models.CharField(max_length=100,blank=True,null=True)
    consultation_fee = models.IntegerField(null=True)
    created = models.DateField(default=timezone.now)
    def __str__(self):
        return self.doctor.username
    
    
 


class Bookings(models.Model):

    status = (('approved', 'approved'),
              ('pending', 'pending'),
              ('rejected', 'rejected'),)
    choice = (('completed','completed'),
               ('absent','absent'),
               ('pending','pending'))

    patient = models.ForeignKey(User, on_delete=models.CASCADE,related_name='patient')
    doctor = models.ForeignKey(User, on_delete=models.CASCADE,related_name='doctor')
    Name = models.CharField(max_length=50,blank=True,default='your name',null=True)
    Phone = models.CharField(max_length=12,null=True,default='contact number')
    Email = models.EmailField(default='example@gmail.com')
    booking_time = models.DateField()
    description = models.TextField(blank=True)
    booking_status = models.CharField(default='pending',choices=status,max_length=100)
    treatment_status = models.CharField(max_length=100,choices=choice,default='pending')


class Feedback(models.Model):
    FEEDBACK_TYPE_CHOICES = [
        ('feedback', 'Feedback'),
        ('complaint', 'Complaint'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    feedback_type = models.CharField(max_length=20, choices=FEEDBACK_TYPE_CHOICES)
    message = models.TextField()
    submitted_at = models.DateTimeField(auto_now_add=True)
    is_resolved = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} - {self.feedback_type}"

templates/admin_dashboard.html
{%extends 'admin.html' %}
{% load static %}
{%block extra_css%}
    <link rel="stylesheet" href="{% static 'css/admin_dashboard.css' %}">
{%endblock%}    
{%block content %}
       <div class="adminpage">
             
           <div class="aprove_sec">
                
                <div class="sidebar">
                   
                    <a href="{%url 'manage_doctors'%}">
                         <div class="sidebar_options">
                          <p>Manage Doctors</p>
                         </div>
                    </a>
                    <a href="{% url 'manage_patients'%}">
                         <div class="sidebar_options">
                          <p>Manage Patients</p>
                         </div>
                    </a>
                  
                   
                   <a href="{%url 'manage_all_appointments'%}">
                        <div class="sidebar_options">
                        <p>Manage Appointments</p>
                        </div>
                   </a>
                   <a href="{%url 'feedback_list'%}">
                        <div class="sidebar_options">
                        <p>Feedbacks/Complaints</p>
                        </div>
                   </a>
                   
                   
                   
                   
                   
                </div>
                <div class="content_sec">
                     <h1>Welcome to Your Admin Panel !</h1> 
                     <div class="buttons">
                    
                          <a href="{% url 'alldoctors' %}">
                            <div class="d1">
                                 <p>Doctors</p>
                                 <p>{{doctor_count}}</p> 
                            </div>
                          </a>
                          <a href="{% url 'allpatients'%}">
                            <div class="d2 d1">
                                <p>Patience</p>
                                <p>{{patient_count}}</p>
                           </div>
                          </a>
                          <a href="{% url 'all_appointments' %}">
                            <div class="d3 d1">  
                              <p>Appointments</p>
                              <p>{{appointment_count}}</p> 
                          </div>
                          </a>
                          
                     </div> 
                    
                </div>
                
           </div>
{%endblock%}              
            

templates/appointment.html
{% extends 'patient_dashboard.html'%}
{% load static %}
{% block extra_css%}
    <link rel="stylesheet" href="{% static 'css/appointment.css' %}">
{%endblock%}    

    {% block content%}

            <div class="maincontent">
                    <div class="title_sec">
                        <h5>TAKING APPOINTMENTS MADE EASY</h5>
                        <p class="p1">Scheduling automation you and your invitees will actually enjoy.</p>
                    </div>
                    <div class="appointment_sec">
                        <a href="{% url 'mybookings' %}">
                            <div class="confirm"><p>Confirmed Appointment</p></div>
                        </a>
                         <div class="description">
                            <img src="{% static 'img/BOOKNMEET-SECURE-MOBILE-SYSTEM-01.svg' %}" alt="">
                            <div class="parag_sec">
                                <p class="p2">BOOKADoc customers can maintain their user / clients data and authorizations for the BOOKADoc 
                                    online mobile appointment scheduling platform.<br><br>

                                    BOOKADoc only creates / confirm affiliates the first time for new customers of the BOOKADoc
                                     online mobile appointment scheduling platform. These users will receive an email containing 
                                     their user ID and initial / default [system generated] password. Note that for security 
                                     reasons, BOOKADoc is not entitled to create and/or administrate additional BOOKADoc online
                                      mobile appointment scheduling platform users for customers after this initial stage.
                                </p>
                            </div>
                         </div>
                    </div>
                    <div class="search_criteria">
                        <div class="list_content">
                            <p class="p2">Several search criteria are available to find the users that the department needs to be 
                                maintained or reassigned to a new department / consultation / speciality:
                            </p>
                            <ul class="p2">
                                <li>Find users by department / speciality / location</li>
                                <li>Find users by name / business / entity / location</li>
                                <li>Find users by service / location / state</li>
                                
                            </ul>
                        </div>

                        <div class="list_content">
                            <p class="p2">The search criteria to find users by service offer three options:</p>
                            <ul class="p2">
                                <li>Any — search only for users who have any authorizations</li>
                                <li>Select search criteria — search only for users who have certain authorizations (listed varified entities)</li>
                                <li>When you select the Select search criteria option, you can search for users with specialities, practice location and location.</li>
                                
                            </ul>
                       </div>

                        <div class="list_content">
                            <p class="p2">Several search criteria are available to find the users that need to be maintained:</p>
                            <ul class="p2">
                                <li>Find users by department</li>
                                <li>Find users by specialities / name</li>
                                <li>Find users by services </li>
                                
                            </ul>
                        </div>

                        <p class="p2">Super administrators are first users of a affliate with maximum authorizations. BOOKADoc 
                            recommends that you create at least two additional super administrators who can support you or substitute 
                            for you if needed. Only super administrators can assign/remove all authorizations from other users / 
                            consultants, since they have all authorizations assigned at the highest possible authorization level. Note
                            that a user administrator cannot administrate himself. A change to his authorizations can only be made by
                            another super administrators or BOOKADoc..
                        </p>
                    </div>

            </div>
    {%endblock%}        

           
    
            

      

templates/aproved_profiles.html
{%extends 'admin.html'%}
{%load static %}
{%block extra_css%}
   <link rel="stylesheet" href="{% static  'css/aproved_profiles.css' %}">
{%endblock%}   

{%block content%}
    <div class="profile_list">
        {% for i in doc %}
          <div class="profile">
                <p>Name : Dr.{{i.doctor}}</p>
                <p>Specialization : {{i.specilization}}</p>
                <p>Location : {{i.location}}</p>
                <p>Phone : {{i.phone}}</p>
                <p>Gender : {{i.gender}}</p>
          </div>
          
        {% endfor %} 
        <a href="{%url 'manage_doctors'%}">
            <button>Back</button>
        </a>  
    </div>
{%endblock%}    

templates/doctor_profile.html
{% extends 'doctor_dashboard.html'%}
{% load static %}
{%block extra_css%}     
    <link rel="stylesheet" href="{% static 'css/doctorprofile.css' %}">
{%endblock%}
       {% block content%} 
         <div class="profile">
                    <div class="profile_sec">
                        <div class="profile_pic">
                          {% if pro.profile_pic%}
                           <img src="{{pro.profile_pic.url}}" alt="profile picture" class="pic">
                          {%else%}
                            <img src="{% static 'img/default.jpg'%}" alt="" class="pic"> 
                          {%endif%} 
                           <div class="div">
                              
                               <p class="username">Dr.{{pro.doctor.username}}</p>
                               <p>id : DC80{{pro.doctor.id}}</p>
                               <p>Registered : {{pro.created}}</p>
                           </div>
                           
                        </div>
                        <div class="personal_info">
                           <p class="profile_title">Personal Informations</p>
                            <div class="info">
                            <p>Full Name</p><p>{{pro.fullname}}</p>
                             </div>
                             <div class="info">
                            <p>Phone</p><p>{{pro.phone}}</p>
                            </div>
                            <div class="info">
                            <p>Email</p><p>{{pro.doctor.email}}</p>
                            </div>
                           <div class="info">
                            <p>Bio</p><p>{{pro.bio}}</p>
                          </div>
                          <div class="info">
                               <p>Gender</p><p>{{pro.gender}}</p>
                          </div>                         
                         <div class="info">
                            <p>Location</p><p>{{pro.location}}</p>
                         </div>
                         <p>Clinic & Profesional Details</p>
                         <div class="info">
                            <p>Specialization</p><p>{{pro.specilization}}</p>
                          </div>
                          
                          <div class="info">
                            <p>Qualifications</p><p>{{pro.qualifications}}</p>
                            </div>
                          
                         <div class="info">
                            <p>Clinic</p><p>{{pro.clinic_name}}</p>
                         </div>
                         <div class="info">
                            <p>Address</p><p>{{pro.clinic_address}}</p>
                         </div>
                         <div class="info">
                            <p>Consultation Days</p><p>{{pro.consultation_days}}</p>
                         </div>
                         <div class="info">
                            <p>Consultation Fee</p><p>{{pro.consultation_fee}}</p>
                         </div>
 
                        <div class="edit">
                             <a href="{% url 'edit_doctor_profile' %}">
                           <input type="button" value="Edit Profile">
                        </a>
                        </div>
                                              
                        
                    </div>
                        <div class="history">
                           <h4>Appointment History</h4>
                           <div class="appointment_list">
                              <ul>
                                 {% for i in booking %}
                                 <li>{{i.booking_time}} - {{i.patient}} | {{i.booking_status}}</li>
                                 {%empty%}
                                 <p>you have no appointments</p>
                                 {%endfor%}
                              </ul>
                           </div>
                        </div>
                    </div>
            </div>

       {%endblock%}  
         

templates/feedback_list.html
{% extends 'admin_dashboard.html'%}
{% load static%}
{% block extra_css%}
<link rel="stylesheet" href="{% static 'css/feedbacklist.css'%}">
{%endblock%}
{% block content%}   
    <div class="feedback">
            <h2>All Feedbacks & Complaints</h2>
            <table>
            <thead>
                <tr>
                <th>User</th>
                <th>Type</th>
                <th>Message</th>
                <th>Date</th>
                <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for fb in feedbacks %}
                <tr>
                <td>{{ fb.user.username }}</td>
                <td>{{ fb.get_feedback_type_display }}</td>
                <td>{{ fb.message }}</td>
                <td>{{ fb.submitted_at }}</td>
                
                {% if fb.is_resolved%}
                <td class="status-resolved">Resolved</td>
                {%else%}
                <td class="status-pending">Pending</td>
                {%endif%}
            
                </tr>
                {% endfor %}
            </tbody>
            </table>
    </div>
{%endblock%}    

templates/login.html
{%extends 'patient_dashboard.html'%}
{% load static %}
{% block extra_css%}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{%endblock%}    


{%block content%}
    
        
   
           <div class="login">
                <form method="post" class="loginform">
                    {% csrf_token %}
                        
                        <h2>Login to your Account</h2><br>
                        <p><label for="">Username : </label>
                        <input type="text" placeholder="Username" class="login_input" name="username"></p>
                        <p><label for="">Password : </label>
                        <input type="password" placeholder="Password" class="login_input" name="password"></p>
                        
                        <input type="submit" value="Login" class="loginbtn">
            
                </form>
        </div>
   
        
{%endblock%}        
        

templates/manage_all_appointments.html
{%extends 'admin.html' %}
{%load static%}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/all_patients.css' %}">
{%endblock%}

{%block content %}
<div class="content">
    <div class="table_sec">
        <table>
            
            <tr>
                <td>Booking id</td>
                <td>Patient</td>
                <td>Doctor</td>
                <td>Booking Date</td>
                <td>Booking Status</td>
                <td>Description</td>
            </tr>
            {%for i in appointments %}
            <tr>
                <td>{{i.id}}</td>
                <td>{{i.patient}}</td>
                <td>{{i.doctor}}</td>
                <td>{{i.booking_time}}</td>
                <td>{{i.booking_status}}</td>
                <td>{{i.description}}</td>
                <td>
                 <a href="{% url 'delete_appointment' i.id %}" 
                       onclick="return confirm('Are you sure you want to delete this appointment?');">
                      🗑️ Delete
                 </a>
                </td>
            </tr>
            {%endfor%}
        </table>
        <div class="back">
              <a href="{% url 'admin_dashboard'%}">
                <button>Back</button>
        </a>
        </div>
        
    </div>
</div>
{%endblock%}

templates/manage_patients.html
{%extends 'admin.html' %}
{%load static%}
{%block extra_css%}
<link rel="stylesheet" href="{% static 'css/all_patients.css' %}">
{%endblock%}

{% block content %}
    <div class="content">
       
        <div class="table_sec">
            <table>
                <tr> 
                    <td>Patient id</td>
                    <td>Name</td>
                    <td>Phone</td>
                    <td>Age</td>
                    <td>Gender</td>
                    <td>Profile</td>
                    
                </tr>
                    {%for i in patients%}
                    <tr>
                        <td>{{i.id}}</td>
                        <td>{{i.patient}}</td>
                        <td>{{i.phone}}</td>
                        <td>{{i.age}}</td>
                        <td>{{i.gender}}</td>
                        <td><a href="{% url 'view_patient' i.id %}"><button class="view">view</button></a></td>
                        <td>
                             <a href="{% url 'delete_patient' i.id %}" 
                              onclick="return confirm('Are you sure you want to delete the patient {{i.patient}}?');">
                                🗑️ Delete
                            </a>
                        </td>
                        
                    </tr>
                    {%endfor%}
            </table>
            <div class="back">
                 <a href="{% url 'admin_dashboard'%}">
                <button>Back</button>
            </a>
            </div>
        </div>
        
        
    </div>
{%endblock%}

templates/profile_verification.html
{% extends 'admin.html'%}
{%load static%}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'css/profile_verification.css' %}">
{%endblock%}

{% block content %} 
    <div class="content">
          {% for i in doc %} 
            <div class="doctors">
                <div class="d1">
                   <p>Dr.{{i.doctor}}</p>
                   <p>{{i.specilization}}</p>
                   <p>{{i.location}}</p>
                </div>
                
                <div class="buttons">
                    <a href="{% url 'aprove_profile' i.id %}">
                       <input type="submit" value="Aprove">
                    </a>
                    <a href="{% url 'reject_profile' i.id %}">
                       <input type="submit" value="Reject">
                    </a>
                </div>
                
            </div>
            {%empty%}
                <h2>No doctors profiles available.!</h2>
          {%endfor%}
          <a href="{% url 'manage_doctors' %}">
            <button>Back</button>
          </a>
    </div>       
        
{%endblock%}        

templates/register_staff.html
{%extends 'patient_dashboard.html' %}
{% load static %}
{% block extra_css%}
      <link rel="stylesheet" href="{% static 'css/register.css' %}">
{%endblock%}  

{% block content %}
        <div class="maincontent">
             <div class="title_sec">
                    <h2>Staff Registration</h2>
             </div>
                    
             
            
             <form method="post" class="staff">
             {% csrf_token %}
             <div class="inputs">
                  
                   {{ form.as_p }}

                   <input type="submit" value="Register" class="register">
             </div>
             
            </form>
        </div>
{%endblock%}


templates/scheduled_appointments.html
{% extends 'doctor_dashboard.html'%}
{%load static%}
{% block extra_css%}
<link rel="stylesheet" href="{% static 'css/feedbacklist.css'%}">
{%endblock%}
{%block content%}

        <div class="feedback">
            
                    <h3>Scheduled Appointments</h3>
                    <table>
                        <thead>
                        <tr>
                            <td>Patient</td>
                            <td>Booking Date</td>
                            <td>Description</td>
                            <td>Status</td>
                        </tr>
                        </thead>
                        {%for i in bookings%}
                        <tbody>
                        <tr>
                            <td>{{i.patient}}</td>
                            <td>{{i.booking_time}}</td>
                            <td>{{i.description}}</td>
                            <td>{{i.booking_status}}</td>
                        </tr>
                        </tbody>
                        {%empty%}
                         <h3>You have no appointments scheduled at the moment. !</h3>
                        {%endfor%}
                    
                    </table>
                    
                    
             
        </div>
                
{%endblock%}             

templates/view_patient.html
{%extends 'patient_dashboard.html'%}
{% load static%}
    <!-- external css -->
 {%block extra_css%}    
    <link rel="stylesheet" href="{% static 'css/doctorprofile.css' %}">
 {%endblock%}   

 {%block content%}
             <div class="profile">
                    <div class="profile_sec">
                        <div class="profile_pic">
                          {% if pro.profile_pic%}
                           <img src="{{pro.profile_pic.url}}" alt="profile picture" class="pic">
                          {%else%}
                            <img src="{% static 'img/default.jpg'%}" alt="" class="pic"> 
                          {%endif%} 
                           <div class="div">
                              
                               <p class="username">{{pro.patient.username}}</p>
                               <p>id : PA65{{pro.patient.id}}</p>
                               <p>Registered : {{pro.created}}</p>
                           </div>
                           
                        </div>
                        <div class="personal_info">
                             <div class="info">
                            <p>Phone</p><p>{{pro.phone}}</p>
                            </div>
                            <div class="info">
                            <p>Email</p><p>{{pro.patient.email}}</p>
                            </div>
                           <div class="info">
                            <p>Bio</p><p>{{pro.bio}}</p>
                          </div>
                           <div class="info">
                            <p>Age</p><p>{{pro.age}}</p>
                          </div>
                          <div class="info">
                            <p>Gender</p><p>{{pro.gender}}</p>
                            </div>
                          <div class="info">
                            <p>Blood</p><p>{{pro.blood}}</p>
                         </div>
 
                        <!-- <div class="edit">
                             <a href="{% url 'edit_patientprofile' %}">
                           <input type="button" value="Edit Profile">
                        </a>
                        </div> -->
                                              
                        
                        </div>
                        <div class="history">
                           
                           <div class="back">
                              <a href="{%url 'manage_patients'%}">
                               <button>Back</button>
                              </a>
                           </div>
                           
                        </div>
                    </div>
            </div>
{%endblock%}            
           